@extends('web.layout.page')
@section('content')
<h1>Content</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt lobortis feugiat vivamus at augue eget arcu dictum varius. Feugiat in fermentum posuere urna nec tincidunt praesent semper. Amet aliquam id diam maecenas ultricies mi. Duis at tellus at urna condimentum mattis pellentesque. Non consectetur a erat nam at. Sagittis id consectetur purus ut faucibus pulvinar elementum integer. Laoreet id donec ultrices tincidunt arcu non sodales neque sodales. Aliquam malesuada bibendum arcu vitae elementum. Elementum pulvinar etiam non quam lacus suspendisse faucibus.</p>
<p>Sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus. Eget mi proin sed libero enim sed faucibus. Tincidunt ornare massa eget egestas purus viverra accumsan in. Turpis egestas maecenas pharetra convallis posuere morbi leo. Posuere urna nec tincidunt praesent semper feugiat. Eu mi bibendum neque egestas congue. Malesuada fames ac turpis egestas sed. Pharetra massa massa ultricies mi. Urna nunc id cursus metus aliquam eleifend mi. Ornare arcu odio ut sem nulla pharetra diam.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt lobortis feugiat vivamus at augue eget arcu dictum varius. Feugiat in fermentum posuere urna nec tincidunt praesent semper. Amet aliquam id diam maecenas ultricies mi. Duis at tellus at urna condimentum mattis pellentesque. Non consectetur a erat nam at. Sagittis id consectetur purus ut faucibus pulvinar elementum integer. Laoreet id donec ultrices tincidunt arcu non sodales neque sodales. Aliquam malesuada bibendum arcu vitae elementum. Elementum pulvinar etiam non quam lacus suspendisse faucibus.</p>
<p>Sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus. Eget mi proin sed libero enim sed faucibus. Tincidunt ornare massa eget egestas purus viverra accumsan in. Turpis egestas maecenas pharetra convallis posuere morbi leo. Posuere urna nec tincidunt praesent semper feugiat. Eu mi bibendum neque egestas congue. Malesuada fames ac turpis egestas sed. Pharetra massa massa ultricies mi. Urna nunc id cursus metus aliquam eleifend mi. Ornare arcu odio ut sem nulla pharetra diam.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt lobortis feugiat vivamus at augue eget arcu dictum varius. Feugiat in fermentum posuere urna nec tincidunt praesent semper. Amet aliquam id diam maecenas ultricies mi. Duis at tellus at urna condimentum mattis pellentesque. Non consectetur a erat nam at. Sagittis id consectetur purus ut faucibus pulvinar elementum integer. Laoreet id donec ultrices tincidunt arcu non sodales neque sodales. Aliquam malesuada bibendum arcu vitae elementum. Elementum pulvinar etiam non quam lacus suspendisse faucibus.</p>
<p>Sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus. Eget mi proin sed libero enim sed faucibus. Tincidunt ornare massa eget egestas purus viverra accumsan in. Turpis egestas maecenas pharetra convallis posuere morbi leo. Posuere urna nec tincidunt praesent semper feugiat. Eu mi bibendum neque egestas congue. Malesuada fames ac turpis egestas sed. Pharetra massa massa ultricies mi. Urna nunc id cursus metus aliquam eleifend mi. Ornare arcu odio ut sem nulla pharetra diam.</p>

@endsection